-- Create table for Contact & Sponsors
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'sponsor', 'contact'
  name text not null,
  email text not null,
  message text,
  metadata jsonb -- any extra fields
);

-- Create table for Newsletter
create table subscribers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  active boolean default true
);

-- Enable Row Level Security (RLS)
alter table leads enable row level security;
alter table subscribers enable row level security;

-- Create policies (Allow insert from Anon key if needed, or rely on Service Role in API)
-- For this architecture using Vercel API, we use the Service Role key in the backend,
-- so RLS policies for 'anon' are not strictly required for insertion, but good practice.
create policy "Enable insert for anon (API)" on leads for insert with check (true);
create policy "Enable insert for anon (API)" on subscribers for insert with check (true);
